<<<<<<< HEAD
import Head from 'next/head';
import Image from 'next/image';

import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
=======
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
>>>>>>> origin/main

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>Pronounced OUR mada</title>
        <meta name="description" content="quick Splash page" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.main} style={{ backgroundImage: `url(/pixelated_boats.png)` }} >
      <a href="/under-construction" target="_blank" className={styles.appLink} style = {{ fontSize: '30px', color: '#4285f4'}}>App</a>
        <div className={styles.description}>
          <p>
          &nbsp;
            <code className={styles.code} style={{ fontSize: '60px', color: '#4285f4'}}>OURMADA</code>
          </p>
=======
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
>>>>>>> origin/main
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
<<<<<<< HEAD
            Mission <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <b>We are on a mission to make DAOs better. &nbsp;
              </b>
            
              &nbsp; 
              <br></br>Ourmada is the modular web3 platform that has the tools they need 
=======
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
>>>>>>> origin/main
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
<<<<<<< HEAD
              Talk to us <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Reach out to this link to hear about the latest &nbsp;
            </p>
          </a>

          
=======
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
>>>>>>> origin/main
        </div>
      </main>
    </>
  )
}
